<a href="https://colab.research.google.com/github/Shivammm77/Guess-the-word/blob/main/Guessword.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch.utils.data import dataset, dataloader


In [32]:
# from google.colab import files
# upload = files.upload()
# import zipfile
# path = "/content/next_word.zip"
# ext_path  = "/content/next_word"
# with zipfile.ZipFile(path , 'r') as f:
#   f.extractall(ext_path)

In [ ]:
#  we seprate sentences
# we just make output of evry next word of input first word
# we are creating supervised task of unsupervised task

In [ ]:
# voab
# index
# dictonary {}
# index to embedding
# data preparation - supervised
# model
#  training loop
#

In [ ]:
# !pip install nltk
import nltk
import numpy as np
import pandas as pd
from collections import Counter
import torch
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
document = """About Data Science Mentorship Program

What is the course fee for  Data Science Mentorship Program (DSMP 2.0)
The total course fee for the DSMP course is Rs 10,600. This includes the fee for both DSMP 1.0 and DSMP 2.0

What is the total duration of the course?
The total duration of the course is about 6-8 months.

Are Deep Learning and NLP a part of the DSMP 2.0  course?
No, NLP and Deep Learning both are not a part of this program’s curriculum.

What if I miss a live session? Will I get a recording of the session?
Yes, all our sessions are recorded, so even if you miss a session you can login into our portal and watch the recording as per your convenience.

Where can I find the class schedule?
You will find the class schedule in your course dashboard once you enroll for the course.

What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.


What is the language spoken by the instructor during the sessions?
Hinglish.

How will I be informed about the upcoming class?
You will get mail from our side before every session once you enroll in the course.

Can I do this course if I am from a non-tech background?
Yes, absolutely. However, you’ll need to be consistent.

I am late, can I join the program in the middle?
Absolutely, you can join the program any time.

If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you’re enrolled in the course, you will be able to see all the past content in your dashboard.

Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.

Will we do case studies in the program?
Yes, there are 5 end to end case studies and multiple smaller projects.

Do we offer any student discounts or promo codes?
We do offer discounts on our courses a few times a year, and we announce them through our social media channels.

On how many devices can I watch the videos simultaneously?
You can watch the videos on one device at a time.



Do you provide notes for the lectures?
We do not provide notes for our lectures. We encourage students to make their own notes as it aids in study retention.

What is the difference between being a paid member on your YouTube channel and your website?
While the content on our YouTube channel and website is similar, enrolling through our website offers additional benefits such as doubt clearance support and access to an exclusive community of learners on Discord and more.

Do I get access to your YouTube channel as a paid member after enrolling through your website?
No, the YouTube channel membership is separate from what we offer on our website.

Is there any upcoming batch for the Data Science Mentorship Program?
Currently, we do not have any plans to launch a new batch for DSMP. However, all previous lectures are available as recordings, allowing you to learn at your own pace.

Do you provide doubt clearance for the projects uploaded on CampusX YouTube channel?
We do not provide doubt clearance for any of our videos or projects uploaded on YouTube. However, you can ask your doubts in our Discord channel or in the comments section.






Payment/Registration related questions

Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/

What if I don’t like the course after making the payment? What is the refund policy?
You get a 7 days refund period from the day you have made the payment. To apply for refund, send us an email at support@campusx.in

I am living outside India and I am not able to make the payment on the website. What should I do?
You can contact us by sending a mail at support@campusx.in

I am from Pakistan and I am unable to make the payment?
We currently do not have the option to accept payment from Pakistan directly. If you’d still like to enroll for the course, you may ask a friend or family member living outside Pakistan to make the fee payment on your behalf.

Do you accept PayPal as a payment method?
Yes, we do. Please contact us at support@campusx.in for more details on using PayPal for payment.

I cannot pay the DSMP 2.0 fee as a one-time payment, is there any way to make a payment in installments?
At the moment, we do not have a monthly payment plan for the DSMP 2.0 course. However, if you have financial constraints, you can enroll in DSMP 1.0 by paying 799/- a month. Once you complete the course, you may apply for a discount coupon from the website.


Post registration queries

Till when can I view the paid videos on the website?
You can watch the videos till your subscription is valid, that is 3 years from the date of purchase for DSMP 2.0 and 2 years for DSMP 1.0

Why is lifetime validity not provided?
Because of the low course fee.

Do you assist with personal projects?
We do not provide support for personal projects due to time constraints and current commitments.

Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearing session.



If I join the program late, can I still ask past week doubts?
Yes, just select “past week's doubt” in the doubt clearance google form.

What is the validity of Doubt Support?
You will get doubt support for 1 year from the data of registration.



Certificate and Placement Assistance related queries

What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 10,600
You have to attempt all the course assessments.

I have read that Job Preparation is a part of this program. What comes under Job Preparation?
This is to clarify that Job Preparation does not mean Placement guarantee. We don't guarantee our learners any jobs or for that matter even interview calls. If you are planning to join this course just for placements, we’re afraid that this course might not be the best for you.

Here is what comes under Job Preparation
Portfolio Building sessions.
Interview Questions.
Sessions with industry mentors.
Discussion on Job hunting strategies.
"""
# with open("/content/next_word/1661-0.txt" , 'r') as f:
#   document = f.read()




In [ ]:
token = word_tokenize(document.lower())

In [ ]:
# build vocab
vocab = {'unk' : 0}
for t in Counter(token).keys():
   if t not  in vocab :
      vocab[t] = len(vocab)
len(vocab)

352

In [ ]:
# extract setences
input_sent = document.split('\n')

In [ ]:
# sent to numerical index
def word_to_index (sentence , vocab):
  numerical_sent = []
  for t in sentence :
    if t in vocab :
      numerical_sent.append(vocab[t])
    else :
      numerical_sent.append(vocab['unk'])
  return   numerical_sent

In [ ]:
input_numeric_sent = []
for sent in input_sent:
  input_numeric_sent . append(word_to_index(word_tokenize(sent.lower()) , vocab))


12311

In [ ]:
# input :  1 3 4 5
# outpu : 1,2,3,4,5,6#
# input :  1 3 4
# outpu : 1,2,3,4,5

In [ ]:
train_sequence = []
for sent in input_numeric_sent:
  for  i in range(1 , len(sent)):
    train_sequence.append(sent[ :i+1])


In [ ]:
train = [1,2,3,4,5,6]
train[5]

6

In [ ]:
#  padding like we have diffrent list len in train_sequence so we are adding zeros

len_list = []
for s in train_sequence:
  len_list.append(len(s))
max(len_list)

56

In [ ]:
# adding zeros doing padding
padded_train_sequance = []
for s in train_sequence:
     padded_train_sequance.append([0]*(max(len_list)-len(s)) + s)
# eg - len_list = 29
#  s = [1,2]
# padded_train_sequance = [0,0,0,0,0,0....0 ,1,2]

In [ ]:

import torch

# converrt it into tensor
padded_train_sequance = torch.tensor(padded_train_sequance , dtype = torch.long)
padded_train_sequance[9]

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10,
        11,  2])

In [ ]:
# i dont know why we did this
x  = padded_train_sequance[: , :-1]
y  = padded_train_sequance[: , -1]

In [ ]:
x

tensor([[   0,    0,    0,  ...,    0,    0,    2],
        [   0,    0,    0,  ...,    0,    2,    3],
        [   0,    0,    0,  ...,    2,    3,    4],
        ...,
        [   0,    0,    0,  ...,  121,  588, 1172],
        [   0,    0,    0,  ...,  588, 1172,  417],
        [   0,    0,    0,  ..., 1172,  417, 9112]])

In [ ]:
class CustomDataset(Dataset):
  def __init__(self , x ,y):
    super().__init__()
    self.x = x
    self.y = y
  def __len__(self):
    return self.x.shape[0]
  def __getitem__(self, idx) :
      return self.x[idx] , self.y[idx]



In [ ]:
dataset = CustomDataset(x,y)
len(dataset)
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [ ]:
dataloader = DataLoader(dataset , batch_size=32 ,shuffle=True)

x.shape
import torch.nn as nn

In [ ]:

class Lstmmodel(nn.Module):
  def __init__(self, vocab_size) :
    super().__init__()
    self.emebbding = nn.Embedding(vocab_size , 100)
    self.lstm = nn.LSTM(100 , 150 , batch_first=True)
    self.fc = nn.Linear(150 , vocab_size)

  def forward(self , x):
    embedd  = self.emebbding(x)
    intermediate_hidden_state , (final_hidden_state , final_cell_state) =  self.lstm(embedd)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [ ]:
model = Lstmmodel(len(vocab))

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
model.to(device)

Lstmmodel(
  (emebbding): Embedding(9399, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=9399, bias=True)
)

In [ ]:
epochs = 50
lr = 0.001
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters() , lr =lr)


In [ ]:
# training loop
for epoch in range(epochs):
  total_loss = 0
  for batch_x , batch_y in dataloader:
    # btach_x , batch_y = batch_x.to(device), batch_y.to(device)
    optimizer.zero_grad()
    output = model(batch_x)
    loss = criterion(output , batch_y)
    loss.backward()
    optimizer.step()
    total_loss = total_loss + loss.item()
  print(f"Epoch : {epoch + 1} , Loss : {total_loss : .4f}")

Epoch : 1 , Loss :  208.5182
Epoch : 2 , Loss :  184.2201
Epoch : 3 , Loss :  170.2968
Epoch : 4 , Loss :  155.8450
Epoch : 5 , Loss :  141.4491
Epoch : 6 , Loss :  127.7376
Epoch : 7 , Loss :  114.5826
Epoch : 8 , Loss :  102.0459
Epoch : 9 , Loss :  90.7861
Epoch : 10 , Loss :  80.2487
Epoch : 11 , Loss :  70.5333
Epoch : 12 , Loss :  61.5038
Epoch : 13 , Loss :  53.8374
Epoch : 14 , Loss :  46.9143
Epoch : 15 , Loss :  40.7958
Epoch : 16 , Loss :  35.4512
Epoch : 17 , Loss :  31.3443
Epoch : 18 , Loss :  27.5053
Epoch : 19 , Loss :  24.3897
Epoch : 20 , Loss :  21.6568
Epoch : 21 , Loss :  19.3483
Epoch : 22 , Loss :  17.4470
Epoch : 23 , Loss :  15.8485
Epoch : 24 , Loss :  14.5074
Epoch : 25 , Loss :  13.3528
Epoch : 26 , Loss :  12.4106
Epoch : 27 , Loss :  11.5928
Epoch : 28 , Loss :  10.7921
Epoch : 29 , Loss :  10.0556
Epoch : 30 , Loss :  9.6168
Epoch : 31 , Loss :  9.0423
Epoch : 32 , Loss :  8.6423
Epoch : 33 , Loss :  8.1911
Epoch : 34 , Loss :  7.8798
Epoch : 35 , Loss : 

In [25]:
def prediction(model , vocab , text):
  # tokenize
  tokensize = word_tokenize(text.lower())
  # print(tokensize)
  # text - > number
  numerical_text = word_to_index(tokensize , vocab)
  # print(numerical_text)
  # padding
  padded_text = torch.tensor([0] * (56 - len(numerical_text)) + numerical_text , dtype = torch.long).unsqueeze(0)

 #  send to model
  output = model(padded_text)
  # predicted index
  value , index= torch.max(output , dim =1)

  #  merge with text
  return text + " "+ list(vocab.keys())[index]

In [26]:
prediction(model , vocab , "i am ")

'i am  late'

Cloning into 'Guess-the-word'...


In [33]:

# i = nn.Embedding(9399 , 100)
# j = nn.LSTM(100 , 150 , batch_first=True)

In [ ]:
# a = dataset[0][0].unsqueeze(0)

In [ ]:
# b = i(a)

In [ ]:
# c ,d =j(b)
# c = hiden sets
# d= e, f
# e = ct

In [ ]:
# c.shape

torch.Size([1, 28, 150])